### ISSUE TITLE
com.learnopengles.android.R.java not found

### ISSUE THREAD

**Issue by aroopganguly** [learnopengles/Learn-OpenGLES-Tutorials#1]
I pulled the repository recently. But when I tried to import the project into Eclipse, I get this compile time error in every file that references com.learnopengles.android.R. And right enough there is no such file. I personally believe that this should have been generated inside eclipse automatically in the "gen [Generated Java Files]" folder.. 

But has anyone else faced this issue? how to fix this?

**Comment by aroopganguly** [comment]
ok, this is some weird Eclipse import error. If I do everything from the scratch then this works. Create a new project and then create these folders under res for raw, drawable etc then all the references are done. frustrating but amazing.

**Comment by learnopengles** [comment]
Hi Aroop,

This is strange -- the R doesn't show up even after rebuilding the project?
Do you see any other errors or warnings?

Thanks!

On Wed, Jul 11, 2012 at 5:04 PM, Aroop <
reply@reply.github.com

**Comment by aroopganguly** [comment]
I fixed the issue by creating a new project and copying these files in the "res" folder. R was generated then. 
This is a snag in Eclipse, where somethings need to "done" specifically by eclipse and the settings cannot be imported as-is from 
an existing project.

This is fixed now. I can close this issue, if you think this is fine.

**Comment by learnopengles** [comment]
Hi Aroop,

Yes, it could also be a snag with the adt. Thanks for letting me know. :)
On Jul 13, 2012 11:01 AM, "Aroop" <
reply@reply.github.com>
wrote:

**Comment by TheDiamondYT1** [comment]
Or you could just add import com.learnopengles.Android.R as it says xD

**Comment by TheDiamondYT1** [comment]
Wow this was inactive for a while

**Comment by learnopengles** [comment]
Yeah, shouldn't happen anymore anyways with the new Android Studio support. ;)
