### ISSUE TITLE
Gradle project?

### ISSUE THREAD

**Issue by denisk20** [learnopengles/Learn-OpenGLES-Tutorials#3]
Hi,
I'm going through your great OpenGL tutorials, and I have converted Android part of your project to be built with Gradle:
https://github.com/denisk20/AndroidOpenGLESLessons
I have added necessary build configuration and removed libgdx references, preserving everything else.
Would you be interested in splitting this repository into 2 parts (OpenGL and WebGL) and me creating a pull request for OpenGL part with gradle configs? It would make it much easier for people to use since the project would be Android Studio-ready out of the box.

**Comment by learnopengles** [comment]
Sure thing, that would be neat. :) It's separated by folder right now so the pull request could be rebased and applied to the Android folder, I believe; would you need me to do anything else?

**Comment by denisk20** [comment]
I can create the pull request for the folder if you'd like to keep the structure the way it is right now, I just thought that separate repositories would be easier to manage.

**Comment by learnopengles** [comment]
Hi Denis, for right now doing it against the current structure would probably be better, as otherwise I might have more than a few links to update. :)

**Comment by denisk20** [comment]
Sure, this is what I thought too. Please take a look at the pull request when you have time, thanks.

**Comment by learnopengles** [comment]
Thanks Denis, this is much appreciated!

**Comment by learnopengles** [comment]
Tested, compiles and runs OK. :) Thanks again!

**Comment by elect86** [comment]
I get this:

> Error running LessonOneActivity: The activity must be exported or contain an intent-filter

**Comment by learnopengles** [comment]
Hi, please let me know how you imported the project. I imported "AndroidOpenGLESLessons" into Android Studio and ran the "app" target. This error sounds like it might happen if the project package is changed as the class names in AndroidManifest.xml are relative class names, not absolute class names.

**Comment by elect86** [comment]
Hi,

I just managed to fix it following [this](http://stackoverflow.com/a/41780556/1047713)

I was trying to run directly the i-th activity...[](url)

**Comment by learnopengles** [comment]
Ah that makes sense, glad you got it working :)
