### ISSUE TITLE
Can't post comments to http://www.learnopengles.com/android-lesson-two-ambient-and-diffuse-lighting/

### ISSUE THREAD

**Issue by denisk20** [learnopengles/Learn-OpenGLES-Tutorials#6]
Hi Kevin,
I wanted to post a comment here
http://www.learnopengles.com/android-lesson-two-ambient-and-diffuse-lighting/
(the link "This website best explains why we have to do this" looks broken). However, I'm getting an error:
![image](https://cloud.githubusercontent.com/assets/3080318/23630343/781b71ec-02c3-11e7-8f94-6a2f5c62e55e.png)
I'm pretty sure that I have cookies and javascript enabled in my Chrome :)

**Comment by learnopengles** [comment]
Hi, you're right, seems I haven't gotten a single comment in a while. I updated the plugins and it seems to be working now. I'll also redirect that link to webarchive or some equivalent. :)

**Comment by denisk20** [comment]
Thanks! Your site is a treasure chest, glad to have it fully working again :)
